package Property;

public class PlaceConstants { // 부지 데이터
    final public static String[] PLACE_NAME = {
            "START",
            "교문",
            "세종냥이집",
            "",
            "학관식당",
            "제주몰빵",
            "지그재그",
            "<html><div style='text-align: center;'>군자의<BR>밥상</div></html>",
            "<html><div style='text-align: center;'>군자관<BR>복사실</div></html>",
            "",
            "컴공과실",
            "LAB-D",
            "<html><div style='text-align: center;'>광개토<BR>ATM</div></html>",
            "진관키친",
            "카지노",
            "",
            "스터디룸",
            "창의토론라운지",
            "헬기장",
            "학실",
            "<html><div style='text-align: center;'>헨델과<BR>그레텔</div></html>",
            "",
            "율지",
            "<html><div style='text-align: center;'>이노베이션<BR>센터</div></html>"};

    final public static String[] PLACE_LINE_NAME = {
            "START",
            "교문",
            "세종냥이집",
            "",
            "학관식당",
            "제주몰빵",
            "지그재그",
            "군자의 밥상",
            "군자관 복사실",
            "",
            "컴공과실",
            "LAB-D",
            "광개토 ATM",
            "진관키친",
            "카지노",
            "",
            "스터디룸",
            "창의토론라운지",
            "헬기장",
            "학실",
            "헨델과 그레텔",
            "",
            "율지",
            "이노베이션 센터"};

    final public static int[] LAND_PRICE = { // 부지 가격
            20, // 월급
            5,
            8,
            0,
            10,
            12,
            0,
            14,
            14,
            0,
            15,
            18,
            0,
            22,
            22,
            0,
            25,
            28,
            0,
            30,
            32,
            0,
            35,
            100
    };

    final public static int[] LAND_TOLL = { // 부지 통행료
            0,
            3,
            5,
            0,
            7,
            10,
            0,
            12,
            12,
            0,
            13,
            16,
            0,
            20,
            20,
            0,
            23,
            26,
            0,
            28,
            30,
            0,
            33,
            50,
    };
    // 매각 = (부지 가격) - 2

    final public static int[] HOUSE_PRICE = { // 집 가격
            0,
            3,
            3,
            0,
            3,
            3,
            0,
            5,
            5,
            0,
            5,
            5,
            0,
            7,
            7,
            0,
            7,
            7,
            0,
            9,
            9,
            0,
            9,
            12
    };
    // 통행료 : +3 , 이.센 통행료: +5

    final public static int[] BUILDING_PRICE = {
            0,
            8,
            8,
            0,
            8,
            8,
            0,
            10,
            10,
            0,
            10,
            10,
            0,
            12,
            12,
            0,
            12,
            12,
            0,
            14,
            14,
            0,
            14,
            20
    };

    final public static int[] HOTEL_PRICE = {
            0,
            12,
            12,
            0,
            12,
            12,
            0,
            15,
            15,
            0,
            15,
            15,
            0,
            18,
            18,
            0,
            18,
            18,
            0,
            21,
            21,
            0,
            21,
            30,
    };

    final public static int[] LANDMARK_PRICE ={
            0,
            20,
            21,
            0,
            22,
            23,
            0,
            24,
            25,
            0,
            26,
            27,
            0,
            28,
            29,
            0,
            30,
            31,
            0,
            32,
            33,
            0,
            34,
            50
    };

    final public static int[] LANDMARK_TOLL = { // 랜드마크 통행료
            0,
            30,
            33,
            0,
            36,
            39,
            0,
            40,
            43,
            0,
            46,
            49,
            0,
            50,
            53,
            0,
            56,
            59,
            0,
            60,
            63,
            0,
            66,
            200
    };

    final public static String[] BUILDING_URL={
            "./image/building/house",
            "./image/building/building",
            "./image/building/hotel"};
}
