package Property;

public class PlaceConstants {
    final public static String[] PLACE_NAME = {
            "START",
            "교문",
            "세종냥이집",
            "",
            "학관식당",
            "제주몰빵",
            "지그재그",
            "<html><div style='text-align: center;'>군자의<BR>밥상</div></html>",
            "<html><div style='text-align: center;'>군자관<BR>복사실</div></html>",
            "",
            "컴공과실",
            "LAB-D",
            "<html><div style='text-align: center;'>광개토<BR>ATM</div></html>",
            "진관키친",
            "카지노",
            "",
            "스터디룸",
            "창의토론라운지",
            "헬기장",
            "학실",
            "<html><div style='text-align: center;'>헨델과<BR>그레텔</div></html>",
            "",
            "율지",
            "<html><div style='text-align: center;'>이노베이션<BR>센터</div></html>"
    };
    final public static int[] PRICE = { // 부지 가격
            20, // 월급
            5,
            8,
            0,
            10,
            12,
            0,
            14,
            14,
            0,
            15,
            18,
            0,
            22,
            22,
            0,
            25,
            28,
            0,
            30,
            32,
            0,
            35,
            100,
    };
}
