public class PlaceConstants {
    final public static String[] PLACE_NAME = {
            "START",
            "교문",
            "세종냥이집",
            "",
            "학관식당",
            "제주몰빵",
            "지그재그",
            "군자의 밥상",
            "군자관\n복사실",
            "",
            "컴공과실",
            "LAB-D",
            "광개토관 ATM",
            "진관키친",
            "카지노",
            "",
            "스터디룸",
            "창의토론라운지",
            "헬기장",
            "학실",
            "헨델과\n그레텔",
            "",
            "율지",
            "이노베이션센터"};
}
